# Site settings
title: Meyer Lab
email: hmeyer@cshl.edu
url: https://example.github.io


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff #86bda6
  secondary: 6699cc #3e6259
  secondary-dark: a23e48 #86bda6
  active: ff8c42 #EE6C4D
  link: 4c243b #2274a5
  text: 4a6c6f #2274a5

# Postal address (add as many lines as necessary)
address:
  - line: Simons Center for Quantitative Biology
  - line: Cold Spring Harbor Laboratory
  - line: Cold Spring Harbor, NY 11724

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# include
include: ["_pages"]

# Build settings
markdown: kramdown
permalink: pretty
