# Site settings
title: Meyer Lab
email: hmeyer@cshl.edu
url: https://example.github.io

setup:
  - name: Home
    link: home
  - name: People
    link: people
  - name: Research
    link: research
  - name: Publications
    link: publications
  - name: Software
    link: software
  - name: Contact
    link: contact

social:
  - title: twitter
    url: http://twitter.com/HannahVMeyer
  - title: github
    url: https://github.com/meyer-lab-cshl

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff #86bda6
  secondary: 6699cc #3e6259
  secondary-dark: a23e48 #86bda6
  active: ff8c42 #EE6C4D
  link: 4c243b #2274a5
  text: 4a6c6f #2274a5

# Postal address (add as many lines as necessary)
address:
  - line: Simons Center for Quantitative Biology
    url: https://www.cshl.edu/research/quantitative-biology/
  - line: Cold Spring Harbor Laboratory
    url: https://www.cshl.edu/
  - line: Cold Spring Harbor, NY 11724

# Credits content
credits: 'Webpage built using Freelancer by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# include
include: ["_pages"]

# Build settings
markdown: kramdown
permalink: pretty
